### ISSUE TITLE
Archivieren der Rohdaten von Parlamentsservern / Nachvollziehbarkeit der Daten (evtl. via Wayback Machine)

### ISSUE THREAD

**Issue by tillprochaska** [HowTheyVote/howtheyvote#14]

**Comment by linusha** [comment]
This might be interesting: https://github.com/agude/wayback-machine-archiver

**Comment by tillprochaska** [comment]
I think you can also simply send a request to `https://web.archive.org/save/{{ URL }}` and it will archive it.
