### ISSUE TITLE
Weitere Formate von VoteTypes

### ISSUE THREAD

**Issue by linusha** [HowTheyVote/howtheyvote#217]
- Visa 11
- Considérant G/2
- Am 9S
- Am 1-65, 67-76
- § 1/1 79
- Split votes?: Article 4, § 3/1
- Considérant 12/2
- Annexxe, partie III/3

https://www.europarl.europa.eu/doceo/document/PV-9-2021-03-09-RCV_FR.pdf

- Am 1-7, 10, 13-14, 17-36, 38-42, 44-48, 50-70, 72-76, 78-80, 83, 87-94, 96-97, 101-102, 104-106, 108-113, 115- 119, 128-132, 137-141, 143-149, 152-153, 155, 157-161, 163-170, 172-190, 192-194, 197-198, 200-202, 204, 206-219, 221, 223-233, 236, 239-242, 244-246, 249, 253-259, 261-276, 278-298, 300-305

https://www.europarl.europa.eu/doceo/document/PV-9-2021-03-10-RCV_FR.pdf

- Certificat vert numérique - ressortissants de pays tiers - Digital Green Certificate - third country nationals - COM(2021)0140 - C9-0100/2021 - 2021/0071(COD - Demande d’application de la procédure d’urgence
- Mise en œuvre des directives sur la qualité de l'air ambiant - Implementation of the Ambient Air Quality Directives - Umsetzung der Luftqualitätsrichtlinien - A9-0037/2021 - Javi López - Proposition de résolution

https://www.europarl.europa.eu/doceo/document/PV-9-2021-03-25-RCV_FR.pdf

**Comment by tillprochaska** [comment]
Wenn ich das richtig sehe, so sind die finalen Abstimmungen in den Abstimmungslisten fast immer mit "Résolution" oder "Proposition de résolution" gekennzeichnet. Das deckt sich auch mit der französischen Übersetzung für die finalen Abstimmungen in der GOEP, z.B. hier auf [Französisch](https://www.europarl.europa.eu/doceo/document/RULES-8-2018-07-31-RULE-171_FR.html) bzw. [Englisch](https://www.europarl.europa.eu/doceo/document/RULES-8-2018-07-31-RULE-171_EN.html).

> finally, voting on the motion for a **resolution as a whole** (final vote).

>  enfin, un vote sur l'ensemble de la **proposition de résolution** (vote final).

Und hier ein Beispiel aus den Abstimmungslisten:

> Droits des enfants - Children's Rights - Rechte des Kindes - B9-0164/2021 - Proposition de résolution

**Comment by linusha** [comment]
Es gibt auch Abstimmungen über Dinge die nicht in Resolutionen enden, oder? Zum Beispiel über die Aufhebung von Immunität. Wie wollen wir mit denen umgehen?

**Comment by tillprochaska** [comment]
Bin mir nicht sicher, ob wir uns vielleicht falsch verstehen, aber mit "proposition de résolution" ist in diesem Kontext keine Motion for Resolution gemeint, sondern einfach die Abstimmung über einen (zuvor möglicherweise geänderten) Text als Ganzes, d.h. es kann eine solche Abstimmung z.B. auch für einen Report geben.

**Comment by tillprochaska** [comment]
Wobei wir da vermutlich noch mal nachlesen sollten, so ganz sicher bin ich mir da dann doch nicht. Gibt aber in jedem Fall solche Fälle, z.B.

> Mécanisme européen d’ajustement des émissions de carbone aux frontières compatible avec l’OMC -
A WTO-compatible EU carbon border adjustment mechanism - Ein mit den WTO-Regeln zu vereinbarendes CO2-Grenzausgleichssystem - A9-0019/2021 - Yannick Jadot - Proposition de résolution

https://www.europarl.europa.eu/doceo/document/PV-9-2021-03-10-RCV_FR.pdf
