### ISSUE TITLE
Fehlerhafte Daten melden

### ISSUE THREAD

**Issue by tillprochaska** [HowTheyVote/howtheyvote#22]

**Comment by linusha** [comment]
@tillprochaska would you still like this?

We have the following on /about:
>If you find a mistake (e.g., wrong data for a vote) or something is not working as expected, we would appreciate if you contact us or open an issue in our [GitHub repository](https://github.com/HowTheyVote/epvotes).

My idea would be another callout at the end of the page, here:

![image](https://user-images.githubusercontent.com/14252419/183121345-db9a681f-fd7c-48d1-b8f2-ef8b16388273.png)

To make sense the option to report needs to be quote prominent imo, and I am unsure if I like it enough for that :see_no_evil:
