### ISSUE TITLE
Infos

### ISSUE THREAD

**Issue by tillprochaska** [HowTheyVote/howtheyvote#44]
* https://www.europarl.europa.eu/germany/resource/static/files/service/handbuch-ordentliches-gesetzgebungsverfahren.pdf
* https://www.europarl.europa.eu/ordinary-legislative-procedure/en/ordinary-legislative-procedure/handbook-on-the-ordinary-legislative-procedure.html
* https://www.europarl.europa.eu/sed/doc/ext/manual/Plenary_guide_en.pdf
* https://www.lehmanns.de/shop/sozialwissenschaften/48246414-9783848757268-das-europaeische-parlament
* https://www.lehmanns.de/shop/sozialwissenschaften/17043600-9780230249820-the-political-system-of-the-european-union

### Änderungsanträge

> If all amendments are rejected, the original text shall be deemed to have been adopted unless a separate vote has been requested within the deadline specified.

> If two or more mutually exclusive amendments have been tabled to the same part of a text, the amendment that departs furthest from the original text shall have priority and shall be put to the vote first. […] However, where the President considers that this will facilitate the vote, he or she may put the original text to the vote first, or put an amendment that is closer to the original text to the vote before the amendment that departs furthest from the original text.

> Where compromise amendments are put to the vote, they shall be given priority in voting.

https://www.europarl.europa.eu/doceo/document/RULES-8-2019-03-25-RULE-174_EN.html

### Split Votes

> Where the text to be put to the vote contains two or more provisions or references to two or more points, or lends itself to division into two or more parts that have a distinct meaning and/or normative value, a split vote may be requested by a political group or Members reaching at least the low threshold.

https://www.europarl.europa.eu/doceo/document/RULES-8-2019-03-25-RULE-176_EN.html

**Comment by tillprochaska** [comment]
@linusha Schau mal hier, es gibt einen Interinstitutional Styleguide, das könnte hilfreich sein: https://publications.europa.eu/code/en/en-120700.htm

**Comment by tillprochaska** [comment]
https://ecpr.eu/Filestore/paperproposal/fb589a2b-eabb-43ec-87c6-99762404246b.pdf

**Comment by tillprochaska** [comment]
https://core.ac.uk/download/pdf/71741453.pdf

**Comment by tillprochaska** [comment]
ACTIVIST GUIDE TO THE BRUSSELS MAZE: https://edri.org/files/2012EDRiPapers/activist_guide_to_the_EU.pdf

**Comment by tillprochaska** [comment]
Lizenz der EP-Daten: 

> As a general rule, the reuse (reproduction or use) of textual data and multimedia items which are the property of the European Union (identified by the words “© European Union, [year(s)] – Source: European Parliament” or “© European Union, [year(s)] – EP”) or of third parties (© External source, [year(s)]), and for which the European Union holds the rights of use, is authorised, for personal use or for further non-commercial or commercial dissemination, provided that the entire item is reproduced and the source is acknowledged.

https://www.europarl.europa.eu/legal-notice/en/ via https://parltrack.org

**Comment by linusha** [comment]
![Screenshot](https://user-images.githubusercontent.com/14252419/129690151-39803fb5-c3e6-4e9f-8a56-34bb4853f433.png)

**Comment by linusha** [comment]
Discharge Procedure: https://www.europarl.europa.eu/committees/en/cont/discharge-procedure/practical-information

**Comment by tillprochaska** [comment]
Statistics: https://www.europarl.europa.eu/plenary/en/bilan-statistic.html

**Comment by linusha** [comment]
<img width="1074" height="1495" alt="Image" src="https://github.com/user-attachments/assets/1a981fa6-7e9f-4a66-aa4f-a1038e4fa821" />

https://www.europarl.europa.eu/cmsdata/297417/Handbook%20on%20the%20Ordinary%20legislative%20procedure_March%202025_EN.pdf, page 40
