### ISSUE TITLE
Add "admin dashboard" package that allows for easier manipulation of DB records

### ISSUE THREAD

**Issue by linusha** [HowTheyVote/howtheyvote#523]
@tillprochaska Ich würde mir das gern anschauen, bzw. mich um Einrichtung und Co kümmern, aber habe bisher keine annähernd sinnvolle Option gefunden.
"Laravel Admin Dashboard" und ähnliches führt im wesentlichen zu so CMS Boards :/ Hast Du eine bessere Idee wonach man sucht, bzw. weißt Du noch was Du da in der Vergangenheit mal benutzt hattest?

**Comment by tillprochaska** [comment]
https://nova.laravel.com/

Habe irgendwo auch eine Lizenz, glaube ich.

**Comment by tillprochaska** [comment]
@linusha Habe die Zugangsdaten im Passwort-Manager abgelegt.
