### ISSUE TITLE
expand csv schema

### ISSUE THREAD

**Issue by twollnik** [HowTheyVote/howtheyvote#528]
The csv download feature is amazing as-is, still I think it could benefit from some enhancements. I would find it really useful if the csv data included more information about the vote: 
- date
- resolution name
- adopted/not adopted
- vote id

I realize that this information is already present on the website. Still, I believe that it would make data consumers' lives easier if the requested information was also published as part of the csv files.

Thanks so much for your work on this useful project!

**Comment by linusha** [comment]
Ich sehe spontan zwei Möglichkeiten zusätzliche Daten zu inkludieren:

1. Die Daten als zusätzliche "konstante" Spalten hinzufügen. Das überzeugt mich nur halb, da es den Sinn einer Tabelle etwas ad absurdum führt. Der Vorteil davon ist, dass es dem CSV Standard entspricht.
2. Wir können zusätzliche Metadaten hinzufügen. Die könnten einem einheitlichen Format folgen. Das ganze ist nicht standardisiert, der W3C Standard für tabulare Daten sagt lediglich, man könnte es zum Beispielsweise durch mit `#` beginnende Zeilen **vor** der Headerzeile machen. Zum Beispiel:

```
# Date: XXX
# Result: Adopted
...
```

Gängige CSV Bibliotheken sowie Excel und LibreOffice bieten die Möglichkeit beim importieren von Daten X Zeilen von Beginn der Datei zu überspringen.

@twollnik meinst Du mit "vote id" die ID des Votes in unserer Datenbank? Welchen Hintergrund hat das? Ein einfacheres wiederfinden des Votes auf der Webseite?

**Comment by tillprochaska** [comment]
@linusha: Wie wäre es, einfach `/votes.csv` für eine Auflistung der Abstimmungen als CSV bereitzustellen, potenziell nach Jahr oder Monat gechunkt?

```csv
id,date,display_title,result,…
1,2021-07-08,"A new ERA for Research and Innovation",adopted,…
2,2021-07-08,"Breaches of EU law and of the rights of LGBTIQ citizens in Hungary",adopted,…
…
```

**Comment by tillprochaska** [comment]
We have recently launched an overhauled version of HowTheyVote.eu, including an experimental API that provides machine-readable access to vote results and vote metadata: https://howtheyvote.eu/developers
