### ISSUE TITLE
Twitter-Bot!

### ISSUE THREAD

**Issue by tillprochaska** [HowTheyVote/howtheyvote#67]
A twitter-bot should take the sharepics generated in #5 and post them on twitter.

**Comment by linusha** [comment]
Should this happen for every vote? Or only for selected ones? In that case we probably do not even need a bot. While I like the idea of having a twitter-bot basically spam-posting these after a plenary session, this might just be annoying and the most important votes are not very visible using this approach.
An option could also be to have a bot-driven account and a "best-of".

**Comment by linusha** [comment]
We want to minimize the manual work necessary.
Solutions in order to not spam:

- only tweet the final votes (i.e. not every amendment)
- make a thread with the votes of the day.
