### ISSUE TITLE
Consider switching to Laravel Pint for code formatting

### ISSUE THREAD

**Issue by tillprochaska** [HowTheyVote/howtheyvote#708]
[Laravel Pint](https://github.com/laravel/pint) is a set of predefined code formatting and linting rules. As `laravel-code-style` (which we’re currently using), it’s built on top of PHP CS Fixer. It’s part of the official Laravel ecosystem. Switching should be as easy as uninstalling `laravel-code-style`, installing Pint, and then reformatting the existing codebase.

**Comment by linusha** [comment]
I do not really have an opinion on this, if you would like to switch we switch. :)
In case we switch - lets make sure that there is exactly one commit that reformats the entire codebase, please.

**Comment by tillprochaska** [comment]
No hard feelings here as well, as long as it’s consistent… :D My assumption is that many Laravel projects will slowly migrate to the official style, and that the probability that the officially maintained rule sets have breaking changes or are deprecated or whatever is lower…
