### ISSUE TITLE
Data repository not available

### ISSUE THREAD

**Issue by sorentv2reg** [HowTheyVote/howtheyvote#918]
Hi

The link to the data repository seems broken:

https://github.com/HowTheyVote/data

Is it possible somehow to get hold of the updated database?

Thanks

**Comment by tillprochaska** [comment]
Hi @sorentv2reg, thanks for opening this issue. We have recently launched a new version of HowTheyVote.eu. Unfortunately, we haven’t been able to re-implement full database exports just yet, but we plan to add this back soon. In the meantime, you can check out our [about page](https://howtheyvote.eu/about) to learn about other ways to reuse data from HowTheyVote.eu.

**Comment by linusha** [comment]
Hey, just a quick update - the data repository is back :slightly_smiling_face: 

However, the format of the data has drastically changed. If, for some reason, you absolutely need the older database (note however, that is is extremely incomplete, outdated and contains errors), please reach out via mail@howtheyvote.eu and I can provide you with it.
